### ISSUE TITLE
Set assumed metadata file encoding to UTF-8

### ISSUE THREAD

**Issue by dlukes** [korpling/pepper#102]
The `pepper.before.readMeta` general customization property leverages `java.util.Properties`, which assumes latin-1 as the text encoding. This doesn't seem like a reasonable default, the encoding should either be configurable (which is perhaps too much work for too little gain) or hardcoded to UTF-8.

This can easily be achieved by wrapping the `FileInputStream` [in the `readMeta()` method](https://github.com/korpling/pepper/blob/develop/pepper-framework/src/main/java/org/corpus_tools/pepper/impl/BeforeAfterAction.java#L510) in an `InputStreamReader`, as detailed in [this article](http://javahowto.blogspot.cz/2014/07/javautilproperties-and-character.html).

The result might look something like [this](https://github.com/dlukes/pepper/commit/57ff51c9091b43f808b0967237a65135d3054545). Though fair warning, I'm no Java expert and though the code does compile, I wasn't able to get a fully working Pepper setup to test it, `mvn clean install assembly:single` (as recommended [here](https://korpling.github.io/pepper/doc-snapshot/developers.html)) doesn't generate any result that I would be able to figure out how to use without learning a lot more about how the individual parts of Pepper fit together... :)

**Comment by FlorianZipser** [comment]
Thanks for pointing this out and thank you for your contribution. If you have further suggestions or improvements please let us know.

**Comment by FlorianZipser** [comment]
Concerning your question: running mvn install assembly:single should create a zip file in the folder PEPPER_SRC/pepper-lib/target/distribution. You can unpack this zip file and have a full Pepper instance with its default modules. To install all available modules, you can run pepper via 
pepper.sh or pepper.bat
and run the command update. Does this help you any further?

**Comment by dlukes** [comment]
Thanks for the merge and all the great work on Pepper and other software for linguistics :)

> a zip file in the folder PEPPER_SRC/pepper-lib/target/distribution. [...] Does this help you any further?

Indeed it does, thank you very much, I'm an idiot, I thought `PEPPER_SRC/target/distribution/pepper-3.1.0-SNAPSHOT.zip` was supposed to be the resulting Pepper instance, which upon decompression it clearly isn't, so I thought some additional manual assembly was necessary :)

**Comment by sdruskat** [comment]
@dlukes I've run into the same issue myself, so @thomaskrause & @FlorianZipser, we should definitely document this more visibly!

**Comment by FlorianZipser** [comment]
I added a sentence to the documentation (I am sorry, that this documentation is very poor in general). Would this help? See https://korpling.github.io/pepper/doc-snapshot/developers.html

**Comment by dlukes** [comment]
> Would this help?

That's perfect!

> I am sorry, that this documentation is very poor in general

No worries, there's only so many hours per day, and what counts most is that all your team is always super helpful and quick to respond on GitHub :)

**Comment by FlorianZipser** [comment]
Thanks you ;)
