### ISSUE TITLE
Output paths with a dot get changed to underscores

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/pepper#36]
I originally thought this was a problem with the relANNIS exporter, but it seems with any exporter module, if the export path contains a period (dot), this automatically gets changed to an underscore. It should be possible for paths to contain periods (some corpus names have them, so this is crucial for PAULA export as well).

**Comment by FlorianZipser** [comment]
Hm, I just tried the following:
<pepper>
	<importer name="PAULAImporter" path="./paula/pcc2.a.b.c"/>
	<exporter name="RelANNISExporter" path="./relANNIS"/>
</pepper>
Which actually is the pcc2 corpus and I just changed the name to pcc2.a.b.c to try to emulate the problem you described. But under ubuntu and Windows 7 (in my virtual machine) as well I got the following result (corpus.tab):

0	paula	CORPUS	NULL	0	7
1	pcc2.a.b.c	CORPUS	NULL	1	6
2	4282	DOCUMENT	NULL	2	3
3	11299	DOCUMENT	NULL	4	5

which seems to be correct. Did I understand the problem correctly? Can you please send me a corpus having that problem?

**Comment by amir-zeldes** [comment]
Hi,

 

It’s true, corpus.tab is generated correctly, this isn’t the problem I mean. The problem is that the actual output folder in the file system where the output relANNIS data is written out to is named wrong. So if I specify an output folder abc.xyz_relANNIS/, Pepper creates abc_xyz_relANNIS/ with an underscore, and outputs the tab files there (but inside corpus.tab, the corpus name is correct with a period).

 

Is that more clear? Thanks,

Amir

**Comment by FlorianZipser** [comment]
Now I tried the following:
<pepper>
	<importer name="PAULAImporter" path="./paula"/>
	<exporter name="RelANNISExporter" path="./abc.xyz_relANNIS/"/>
</pepper>
But I got an output folder as expected: abc.xyz_relANNIS/
Can you try to reproduce with the newest snapshot: https://korpling.german.hu-berlin.de/saltnpepper/pepper/download/snapshot/Pepper_2015.04.21-SNAPSHOT.zip

May be the problem is already solved somehow, or did I still got you wrong?

**Comment by amir-zeldes** [comment]
Hallo Florian,

 

nein, das Problem ist immer noch da. Das ist für jedes Korpus reproduzierbar (wenigstens mit relANNIS als Ausgabe). Den Fehler sieht man schon in der DOS-Ausgabe.

 

Params:

<exporterParams formatName="relANNIS" formatVersion="3.2" destinationPath="file:/C:/Pepper/corpora/sahidica.1corinthians_relANNIS/"/>

 

STDOUT: 

…

+----------------------------------- step 3 ------------------------------

 

|exporter:      RelANNISExporter

 

|path:          file:/C:/Pepper/corpora/sahidica_1corinthians_relANNIS

 

|properties:    - none -

 

|

 

Ich kann Dir das Korpus auch schicken, aber wie gesagt, das passiert mit jedem Punkt in jedem Korpus-Pfad. Der Korpus-Name in corpus.tab stimmt trotzdem. Das läuft alles unter Win7 64, Java:

 

c:\Pepper>java -version

java version "1.8.0_31"

Java(TM) SE Runtime Environment (build 1.8.0_31-b13)

Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

 

Angenommen Du kannst das nicht reproduzieren, hast Du eine Idee, was ich noch testen kann?

 

Danke!

Amir

**Comment by FlorianZipser** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Amir,

ja schick mir doch bitte mal das Korpus mit der pepper Datei, am
besten mit relativem Pfad, so dass ich dann haargenau das ausführen
kann, was Du bei Dir laufen lässt. Ich habe ja noch die Vermutung,
dass vielleicht irgendwetwas anders ist bei Deinem Korpus im Vergleich
zu meinem Beispiel auf github. zumindest hoffe ich das.
Ich habe das unter Ubuntu und ebenfalls Win7 64 ausprobiert,
allerdings in der Virtual Machine. Ich glaube aber eigentlich nicht,
dass es daran liegt, oder fände es sehr merkwürdig.

Ciao Florian

Am 23.04.2015 um 17:56 schrieb Amir Zeldes:
> Hallo Florian,
> 
> 
> 
> nein, das Problem ist immer noch da. Das ist für jedes Korpus
> reproduzierbar (wenigstens mit relANNIS als Ausgabe). Den Fehler
> sieht man schon in der DOS-Ausgabe.
> 
> 
> 
> Params:
> 
> <exporterParams formatName="relANNIS" formatVersion="3.2"
> destinationPath="file:/C:/Pepper/corpora/sahidica.1corinthians_relANNI
S/"/>
>
> 
> 
> 
> STDOUT:
> 
> …
> 
> +----------------------------------- step 3
> ------------------------------
> 
> 
> 
> |exporter:      RelANNISExporter
> 
> 
> 
> |path:
> file:/C:/Pepper/corpora/sahidica_1corinthians_relANNIS
> 
> 
> 
> |properties:    - none -
> 
> 
> 
> |
> 
> 
> 
> Ich kann Dir das Korpus auch schicken, aber wie gesagt, das
> passiert mit jedem Punkt in jedem Korpus-Pfad. Der Korpus-Name in
> corpus.tab stimmt trotzdem. Das läuft alles unter Win7 64, Java:
> 
> 
> 
> c:\Pepper>java -version
> 
> java version "1.8.0_31"
> 
> Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
> 
> Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
> 
> 
> 
> Angenommen Du kannst das nicht reproduzieren, hast Du eine Idee,
> was ich noch testen kann?
> 
> 
> 
> Danke!
> 
> Amir
> 
> 
> 
> From: Florian Zipser [mailto:notifications@github.com] Sent:
> Tuesday, April 21, 2015 15:16 To: korpling/pepper Cc: Amir Zeldes 
> Subject: Re: [pepper] Output paths with a dot get changed to
> underscores (#36)
> 
> 
> 
> Now I tried the following:
> 
> 
> 
> 
> But I got an output folder as expected: abc.xyz_relANNIS/ Can you
> try to reproduce with the newest snapshot:
> https://korpling.german.hu-berlin.de/saltnpepper/pepper/download/snaps
hot/Pepper_2015.04.21-SNAPSHOT.zip
>
>  May be the problem is already solved somehow, or did I still got
> you wrong?
> 
> — Reply to this email directly or view it on GitHub
> <https://github.com/korpling/pepper/issues/36#issuecomment-94910525>
> .Image removed by sender.
> 
> 
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/korpling/pepper/issues/36#issuecomment-95632461
> 


- -- 
Florian Zipser
Dipl. Inf.
Institute for German Language and Linguistics
Humboldt-Universität zu Berlin
Unter den Linden 6
D-10099 Berlin

phone: +49 (0)30 2093 9720
mail:  f.zipser@gmx.de
web:   http://u.hu-berlin.de/zipser
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVORmGAAoJEPzXRiHkLJBhNjUIAI2Y4Cca/Y4aRZUACDDuFjIw
TjEbyRRm6MNn219+Euk/LrS+gWyBi+AaxeUhoAvYjsYYrJForT8iGUc3B/jU9BAC
NHgh6QNB7y/DnYkE0FFxRId0TbIsO8g1g02whre7gd2080lHeIyi8/bnYvgqSJAz
2EEnjxJjhJyOHCInJslsd++9hSiMbGNU43IYP+U7A5kV4InPh+V+EHEzMN/gs+ah
YACYy/UYeDklnhiHVDIZFt1yn6qGjSW/GSH4Iz0IXxxe3wacCy9TICza+ulPsbPI
wXkIwc8LxASs4DRpO42GCamqsJdQ3OKV+17ww7Gro6pIQ3REJbURaKmhLw4lU0A=
=zqYB
-----END PGP SIGNATURE-----

**Comment by amir-zeldes** [comment]
Hallo Florian, 

 

hier sind die Daten, allerdings ohne relative Pfade. Vielleicht liegt’s daran? Relative Pfade klappen bei mir seit langer Zeit nicht, aber vielleicht mache ich die Syntax falsch? Wenn Du mir ein Beispiel schickst, kann ich es auch mit relativen Pfaden ausprobieren.

 

Viele Grüße,

Amir
