### ISSUE TITLE
Preserve output files

### ISSUE THREAD

**Issue by FlorianZipser** [korpling/pepper#43]
Implement mechanism to preserve files in output path of exporters. For instance in case of relANNIS or SaltInfoModule, there are some customization files to be adapted. When the user has adapted them he don't want them to be overwritten when converting a second time.

**Comment by FlorianZipser** [comment]
When doing this is general for all modules, the files cannot be preserved, but they can be copied. That means the user can create a kind of backup files, use the customization pepper.after.copyRes having the value 'file1->destination;file2->destination2' to copy such files after conversion automatically.

**Comment by amir-zeldes** [comment]
I'm not sure I understand why in general files can't be preserved: if the user can anticipate the name of a file that should simply not be outputted, why shouldn't this be configurable? For relANNIS, I could say: 
```
noclobber=resolver_vis_map.tab,corpus_annotation.tab
```
And similarly for PAULA output I could say:
```
noclobber=doc1/GUM.GUM_interview_daly.meta_type.xml
```
Since parameter files are per conversion, it's quite likely the user will run the exact same conversion multiple times and can predict the file name. The instruction above just means: "If you're thinking about writing a file called X, just don't do it".

**Comment by FlorianZipser** [comment]
Yes, theoretically is this absolute thinkable. The point is when preserving those files, this must be implemented in each module (as it is the case for relANNISExporter). Currently all modules (except relANNISExporter) just output their files without noticing existing files. To solve the configuration problem for all (or nearly all) modules at once, we choosed the way of copying the files. The result is more or less the same. The only difference is that a copy of the file is needed. Let's take the relANNIS case for instance and the following folder structure:

|-original
|-relANNIS
   |-node.tab
   |-...
   |-resolver_vis_map.tab
|-resolver_vis_map.tab
|-conversion.pepper

With the implemented property you can configure the relANNISExporter as follows:
<exporter name="RelANNISExporter" path="./relANNIS">
  <property key="pepper.after.copyres">resolver_vis_map.tab->relANNIS/resolver_vis_map.tab</property>
</exporter>

The processing will be as follows:
/1/ all files are exported to folder relANNIS (normal behavior)
/2/ copy file resolver_vis_map.tab to folder relANNIS/resolver_vis_map.tab

So the result would be the same. Indeed for the resolver_vis_map this is not necessary, but the implemented mechanism now is available for all modules also for PAULA.

**Comment by amir-zeldes** [comment]
Creating subfolders with added files is actually meaningful in PAULA (it looks like the higher folder is a subcorpus, and the new folder is a document). Wouldn't that cause a problem?

**Comment by FlorianZipser** [comment]
May be there is a misunderstanding, let me write the structure in a slightly different way:

C:\...\original\
C:\...\relANNIS\node.tab
...
C:\...\relANNIS\resolver_vis_map.tab
C:\...\resolver_vis_map.tab
C:\...\conversion.pepper

Using the customization will copy the file C:\...\resolver_vis_map.tab to C:\...\relANNIS\resolver_vis_map.tab at the end of the conversion. So the input won't be changed.
When exporting PAULA the sample could be the following (assuming there is a useful usecase):

C:\...\paula\myCorpus\myDocument1
C:\...\paula\myCorpus\myDocument2
C:\...\fileToCopy.txt
C:\...\conversion.pepper

Using a property like this:

&lt;property key="pepper.after.copyRes">fileToCopy.txt->./paula/myCorpus/</property>

will copy the file C:\...\fileToCopy.txt into the folder C:\...\paula\myCorpus\ .

**Comment by amir-zeldes** [comment]
Oh, OK, I understand. That would not cause the PAULA problem I described. It's still slightly less convenient, since you have to keep a directory of 'replacement files' (C:...\resolver_vis_map.tab in the example). But realistically speaking I would only need this for relANNIS at the moment. The 'noclobber' option for relANNIS still exists, right?

**Comment by FlorianZipser** [comment]
Yes the noclober property still exists or will exists in the next annis exporter version ;-). But it seems we are very close to the release. And yes, you need to keep a replacement folder. Since this is a general possibility this is very helpful for other formats, for instance for the SaltInfoExporter. For exporting the annis format it is more comfortable to use the noclobber property. But I am not sure if noclobber will also preserve the Extdata folder, does it?

**Comment by amir-zeldes** [comment]
So far the relANNIS exporter doesn't produce the extdata folder, so that never gets overwritten. Maybe for corpora with multimedia data in the source corpus (exmaralda?)

**Comment by FlorianZipser** [comment]
Exactly, this could overwrite a customized folder.
