### ISSUE TITLE
Replace instances of "wizzard" with "wizard"

### ISSUE THREAD

**Issue by sdruskat** [korpling/pepper#63]
After all, Pepper is not a UK glam rock band.

[![Wizzard album](http://www.mainartery.co.uk/images/retro/wizzard.jpg)](https://en.wikipedia.org/wiki/Wizzard)

**Comment by FlorianZipser** [comment]
Where did you find them? In the readme.md in develop branch or somewhere else?

**Comment by sdruskat** [comment]
Yes, README.md on the develop branch. No instances in master, so I
guess you're good :).

**Comment by thomaskrause** [comment]
was fixed in 3dcb3ef253d9088f5b1df63d2d380559de6716f6 (which refers to the wrong issue number)
