### ISSUE TITLE
Include version ID in assembly product, root folder name and perhaps readme.txt

### ISSUE THREAD

**Issue by sdruskat** [korpling/pepper#65]
The ZIPs for releases linked to from http://corpus-tools.org/pepper/index.html#download (e.g., those on https://korpling.german.hu-berlin.de/saltnpepper/pepper/download/stable/) have the format Pepper_YYYY.MM.DD.zip. As Pepper uses version numbers internally though (e.g., in error messages during the update process (`No update was performed because of a version incompatibility according to pepper-framework: 
pepperModules-GrAFModules needs 2.1.2, but 2.1.0 is installed!`)), it'd be great to be able to quickly get the version ID for the version one is working with without having to start Pepper.

Therefore, please include version IDs in: 
1. Assembly ZIP file: Pepper_Maj.Min.Pat_YYYY.MM.DD.zip (e.g., `Pepper_2.1.2_2015.07.30.zip`)
2. Root folder in ZIP (is now simply `pepper`, would be great if it was `pepper-2.1.2`, `pepper_2-1-2` or similar).
3. (readme.txt somewhere)

**Comment by FlorianZipser** [comment]
I decided to use option 3 and just commited a version which creates a mashine readable version.txt and adds the version to the readme.txt. Does this solve the problem?
