### ISSUE TITLE
Installing own module with dependencies

### ISSUE THREAD

**Issue by FranklinChen** [korpling/pepper#69]
I have created a Pepper module `pepperModules-CHATModules` which uses JAXB to extract information from XML documents, and therefore the module has dependencies

```xml
    <dependencies>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2.12</version>
        </dependency>
    </dependencies>
```

After `mvn package`, I tried to use `./pepperStart.sh` but installing the module fails. How do I get Pepper to know and pick up the dependencies? I'm not familiar with OSGi, so maybe I'm missing something trivial?

```console
pepper>install_start /Users/chen/pepperModules-CHATModules/target/org.corpus-tools.pepperModules-CHATModules_1.0.0.jar
bundle installed with id '109'.
The bundle 'org.corpus-tools.pepperModules-CHATModules-1.0.0' wasn't started correctly. The bundle is located at 'file:/Users/chen/pepper/./plugins/org.corpus-tools.pepperModules-CHATModules_1.0.0.jar'. This could cause other problems. For more details turn on log mode to debug and see log file.
org.osgi.framework.BundleException: The bundle "org.corpus-tools.pepperModules-CHATModules_1.0.0 [109]" could not be resolved. Reason: Missing Constraint: Import-Package: javax.xml.bind; version="[2.2.0,3.0.0)"
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1332)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1316)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:323)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:300)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:292)
	at org.corpus_tools.pepper.connectors.impl.PepperOSGiConnector.start(PepperOSGiConnector.java:614)
	at org.corpus_tools.pepper.cli.OSGiConsole.start(OSGiConsole.java:276)
	at org.corpus_tools.pepper.cli.OSGiConsole.installAndStart(OSGiConsole.java:294)
	at org.corpus_tools.pepper.cli.PepperStarter.installAndStart(PepperStarter.java:522)
	at org.corpus_tools.pepper.cli.PepperStarter.executeSingleCommand(PepperStarter.java:1065)
	at org.corpus_tools.pepper.cli.PepperStarter.runInteractive(PepperStarter.java:1029)
	at org.corpus_tools.pepper.cli.PepperStarter.main(PepperStarter.java:1234)
The bundle 'org.corpus-tools.pepperModules-CHATModules-1.0.0' wasn't started correctly.
started bundle with id '109'
launched Pepper module
```

**Comment by FlorianZipser** [comment]
In general, a bundle in OSGi can be started when all its dependencies are started inside the OSGi container. That means each library you are using, you need to install in the OSGi environment. 
Pepper automatically installs all jar files which are located in PEPPER_HOME/plugins. But they need to be bundles, otherwise OSGi cannot start them. For JAXB it seems, that there is a bundle available via maven central:
http://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-osgi/2.2.11
 
When you use this dependency and provide your Pepper module in a maven repo, Pepper will automatically retrieve the dependency, download and start it. But for developing you need to download and put it to PEPPER_HOME/plugins on your own (Use the 'Download Jar' link). 
There is another way you can go. You can also embed 3rd party libraries into your module. Therefore you need to adapt the maven bundle plugin:
<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>${maven-bundle-plugin.version}</version>
				<extensions>true</extensions>
				<executions>
					<execution>
						<phase>process-classes</phase>
						<goals>
							<goal>bundle</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<manifestLocation>${META-INF}</manifestLocation>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<instructions>
						<Bundle-Name>${project.artifactId}</Bundle-Name>
						<Bundle-SymbolicName>${project.groupId}.${project.artifactId};singleton:=true</Bundle-SymbolicName>
						<Bundle-Version>${project.version}</Bundle-Version>
						<Bundle-RequiredExecutionEnvironment>JavaSE-${java.version}</Bundle-RequiredExecutionEnvironment>
						<Service-Component>${allServiceComponents}</Service-Component>
						<Bundle-ClassPath>.,{maven-dependencies}, lib/my-jar.jar</Bundle-ClassPath>
						<Include-Resource>{maven-resources}, LICENSE, NOTICE, lib/my-jar.jar=lib/my-jar.jar</Include-Resource>
					</instructions>
				</configuration>
			</plugin>
and put the jar into a lib folder in your modules directory. Then maven will extract the 3rd jar and put the compiled files into your jar, so that your module can resolve these classes.

If this wasn't helpful, don't hesitate to write again.

**Comment by FlorianZipser** [comment]
If I may make a short remark. In case your document are getting large, using JAXB might not be the best choice, since it creates an own main memory model. Depending on the size of your files, the model could get very large and it could be better to use SAX or StAX.

**Comment by FranklinChen** [comment]
- I'm using JAXB because extracting information from a complex tree is much easier that way.
- The `com.sun` thing seemed obsolete, so I grabbed http://central.maven.org/maven2/javax/xml/bind/jaxb-api-osgi/2.2.7/jaxb-api-osgi-2.2.7.jar and put that into `pepper/plugins` (apparently nobody has made a bundle for 2.2.12). This gets me further, also I'm now having other problems to debug.

**Comment by FranklinChen** [comment]
`jaxb-api-osgi` was the wrong choice. It turned out that I needed http://central.maven.org/maven2/com/sun/xml/bind/jaxb-osgi/2.2.7/jaxb-osgi-2.2.7.jar which works. Versions 2.2.10 and 2.2.11 of that are broken, resulting in stuff like

```
org.osgi.framework.BundleException: The bundle "com.sun.xml.bind.jaxb-osgi_2.2.10 [42]" could not be resolved. Reason: Missing Constraint: Import-Package: com.sun.source.tree; version="0.0.0"
```
