### ISSUE TITLE
Implement a helper method to return module properties as arrays

### ISSUE THREAD

**Issue by sdruskat** [korpling/pepper#77]
When implementing properties for new Pepper modules, it would be helpful to be able to return the property value as an array, if the value is passed in as a comma-separated list.

E.g., consider the following property configuration.

```
<property key="listOfStringValues">one, two, three</property>
<property key="listOfBooleanValues">true, false, true</property>
```

In the properties class for the module, you would like to set up the properties as follows.

```
public static final String PROP_STRINGS = "string";
public static final String PROP_BOOLS = "bools";
```

And add the properties as follows.

```
public MyModuleProperties() {
  addProperty(new PepperModuleProperty<>(PROP_STRINGS, 
      String[].class, 
      "An array of strings.", 
      new String[]{"I", "am", "default"},
      false));
  addProperty(new PepperModuleProperty<>(PROP_BOOLS, 
      Boolean[].class, 
      "An array of booleans.", 
      new Boolean[]{true, true, true},
      false));
```

Also, in any potential getter methods, it would be great to return the final data type, such as follows.

```
public String[] getStrings() {
  return getProperty(PROP_STRINGS).toDataTypeSpecificArray();
}
```

**Comment by FlorianZipser** [comment]
Now it should work like this:

PepperModuleProperty.create().withName("prop1").withType(Boolean.class).withDescription("desc").build();
property.setValueString("true, false,true");
assertThat(((PepperModuleProperty<Boolean[]>) property).getValue()).containsExactly(new Boolean[] { true, false, true });

Is that what you needed?

**Comment by FlorianZipser** [comment]
see  #feature/77
