### ISSUE TITLE
SaltNPepper Repo

### ISSUE THREAD

**Issue by MartinKl** [korpling/pepper#8]
enhance SaltNPepperRepo for an ignore list, to not add listed bundles to SaltNPepper bundle. As for instance deprecated bundles like pepper-logReader are always added otherwise. Those must be deleted manually for each release and snapshot release or cause very anoying error messages for the user.

**Comment by sdruskat** [comment]
+1

**Comment by FlorianZipser** [comment]
replaced SaltNPepper repo entirely by update mechanism via maven
